import os
import json
import urllib.request

class SQLTranslationService:
    def __init__(self):
        # 🌐 MUST BE THE FULL PUBLIC CLOUDERA URL GENERATED BY YOUR UI
        # Example: https://mcp.ml-95614b64-f85.ps-amer.a465-9q4k.cloudera.site
        self.mcp_server_url = os.getenv("MCP_SERVER_URL")
        
        # Example: https://qwen.ml-95614b64-f85.ps-amer.a465-9q4k.cloudera.site/v1/chat/completions
        self.qwen_engine_url = os.getenv("QWEN_LLM_URL")
        
        # 🔑 The secure master token used to unlock cross-app traffic
        self.api_token = os.getenv("CML_TOKEN")

    def generate_sql(self, user_question: str) -> str:
        if not self.api_token:
            raise RuntimeError("CRITICAL: 'CML_TOKEN' environment variable is missing on the Backend Application.")

        agent_system_prompt = """You are an advanced text-to-SQL translation agent for a MySQL 8.0 database.

You have access to an internal Model Context Protocol (MCP) tool to read the schema definitions from disk. 

AVAILABLE TOOLS:
- `CALL: get_schema()` : Retrieves table schemas, columns, primary keys, and data relationships.

OPERATIONAL PROTOCOL:
1. Evaluate the user's question. If you do not have the specific table columns or layout required to answer it in your immediate chat history, respond by calling the schema tool: `CALL: get_schema()`.
2. Once the schema is provided to you in the next turn, construct a high-fidelity, optimized MySQL statement.
3. Output your final answer inside a standard markdown ```sql ``` block. Do not provide conversational explanations outside of the code block.

CRITICAL SAFETY BOUNDARIES:
- You are strictly forbidden from writing INSERT, UPDATE, DELETE, or DROP commands."""

        # Clean, un-manipulated user history thread
        messages = [
            {"role": "system", "content": agent_system_prompt},
            {"role": "user", "content": user_question}
        ]

        for turn in range(3):
            payload = {
                "model": "qwen2.5-3b-instruct",
                "messages": messages,
                "temperature": 0.0
            }

            # 🔒 1. Authenticated Secure Handshake to the Qwen Engine App
            try:
                req = urllib.request.Request(
                    self.qwen_engine_url,
                    data=json.dumps(payload).encode("utf-8"),
                    headers={
                        "Content-Type": "application/json",
                        "Authorization": f"Bearer {self.api_token}" # 🔑 Passing the token here
                    },
                    method="POST"
                )
                with urllib.request.urlopen(req, timeout=30) as response:
                    result = json.loads(response.read().decode("utf-8"))
                    ai_response = result["choices"][0]["message"]["content"].strip()
            except Exception as e:
                raise RuntimeError(f"Failed to communicate with Qwen Engine App: {str(e)}")

            print(f"🤖 [Pure MCP Agent - Turn {turn + 1}] Qwen Output:\n{ai_response}\n")

            # 🛠️ FIXED INTERCEPTOR: Case-insensitive, robust phrase matching
            if "get_schema" in ai_response.lower():
                print("📡 Tool Invoked! Fetching layout from MCP Server via secure token channel...")
                try:
                    schema_req = urllib.request.Request(
                        f"{self.mcp_server_url}/api/test/schema",
                        headers={"Authorization": f"Bearer {self.api_token}"},
                        method="GET"
                    )
                    with urllib.request.urlopen(schema_req, timeout=5) as schema_resp:
                        schema_data = json.loads(schema_resp.read().decode("utf-8"))
                        schema_context = schema_data.get("raw_yaml_configuration", "")
                except Exception as e:
                    raise RuntimeError(f"MCP Tool Server communication failed: {str(e)}")

                # Append the dialogue history and feed the true database structure into Turn 2
                messages.append({"role": "assistant", "content": ai_response})
                messages.append({
                    "role": "user", 
                    "content": f"TOOL_RESPONSE (get_schema):\n{schema_context}\n\nReview this schema and execute Step 2 and Step 3 of your protocol."
                })
                continue

            # 🏁 3. Extract final SQL asset when generated
            if "```sql" in ai_response:
                generated_sql = ai_response.split("```sql")[1].split("```")[0].strip()
                return generated_sql
            elif "SELECT" in ai_response.upper():
                return ai_response.replace("```", "").strip()
            
            return ai_response

        raise RuntimeError("Agent Loop Error: Max execution turns exceeded without resolving a statement.")