import os
import json
import urllib.request

class SQLTranslationService:
    def __init__(self):
        # 🌐 MUST BE THE FULL PUBLIC CLOUDERA URL GENERATED BY YOUR UI
        # Example: https://mcp.ml-95614b64-f85.ps-amer.a465-9q4k.cloudera.site
        self.mcp_server_url = os.getenv("MCP_SERVER_URL")
        
        # Example: https://qwen.ml-95614b64-f85.ps-amer.a465-9q4k.cloudera.site/v1/chat/completions
        self.qwen_engine_url = os.getenv("QWEN_LLM_URL")
        
        # 🔑 The secure master token used to unlock cross-app traffic
        self.api_token = os.getenv("CML_TOKEN")

    def generate_sql(self, user_question: str) -> str:
        if not self.api_token:
            raise RuntimeError("CRITICAL: 'CML_TOKEN' environment variable is missing on the Backend Application.")

        agent_system_prompt = """You are an autonomous database routing agent for a MySQL 8.0 cluster. 
You do not have the data schema memorized. You must interact with your available Model Context Protocol (MCP) tools to discover information before outputting code.

AVAILABLE MCP TOOLS:
1. Name: `get_schema()`
   Description: Connects to the local filesystem and reads the master 'domain_config.yaml' file containing table metrics, columns, aliases, and active state rules.

OPERATIONAL INSTRUCTIONS:
- If you do not know the exact column names, table links, or active state rules needed for a query, you MUST request the schema by writing exactly:
  CALL: get_schema()
- Once you receive the tool response with the schema text layout, process the table properties carefully.
- Output your final response as a single, raw MySQL statement wrapped inside a clean ```sql ``` code block. Do not write text explanations outside the code block once you have your answer.

CRITICAL SAFETY BOUNDARIES:
- You are strictly forbidden from writing INSERT, UPDATE, DELETE, or DROP commands."""

        messages = [
            {"role": "system", "content": agent_system_prompt},
            {"role": "user", "content": f"Analyze this request and generate the correct query: {user_question}"}
        ]

        for turn in range(3):
            payload = {
                "model": "qwen2.5-1.5b-instruct",
                "messages": messages,
                "temperature": 0.0
            }

            # 🔒 1. Authenticated Secure Handshake to the Qwen Engine App
            try:
                req = urllib.request.Request(
                    self.qwen_engine_url,
                    data=json.dumps(payload).encode("utf-8"),
                    headers={
                        "Content-Type": "application/json",
                        "Authorization": f"Bearer {self.api_token}" # 🔑 Passing the token here
                    },
                    method="POST"
                )
                with urllib.request.urlopen(req, timeout=30) as response:
                    result = json.loads(response.read().decode("utf-8"))
                    ai_response = result["choices"][0]["message"]["content"].strip()
            except Exception as e:
                raise RuntimeError(f"Failed to communicate with Qwen Engine App: {str(e)}")

            print(f"🤖 [Pure MCP Agent - Turn {turn + 1}] Qwen Output:\n{ai_response}\n")

            if "CALL: get_schema()" in ai_response:
                print("📡 Tool Invoked! Fetching layout from MCP Server via secure token channel...")
                
                # 🔒 2. Authenticated Secure Handshake to the MCP Server App
                try:
                    schema_req = urllib.request.Request(
                        f"{self.mcp_server_url}/api/test/schema",
                        headers={"Authorization": f"Bearer {self.api_token}"}, # 🔑 Passing the token here
                        method="GET"
                    )
                    with urllib.request.urlopen(schema_req, timeout=5) as schema_resp:
                        schema_data = json.loads(schema_resp.read().decode("utf-8"))
                        schema_context = schema_data.get("raw_yaml_configuration", "")
                except Exception as e:
                    raise RuntimeError(f"MCP Tool Server communication failed: {str(e)}")

                messages.append({"role": "assistant", "content": ai_response})
                messages.append({
                    "role": "user", 
                    "content": f"TOOL_RESPONSE (get_schema):\n{schema_context}\n\nReview this data and generate your final raw MySQL statement inside ```sql wrappers."
                })
                continue

            if "```sql" in ai_response:
                generated_sql = ai_response.split("```sql")[1].split("```")[0].strip()
                return generated_sql
            elif "SELECT" in ai_response.upper():
                return ai_response.replace("```", "").strip()
            
            return ai_response

        raise RuntimeError("Agent Loop Error: Max execution turns exceeded without resolving a statement.")